### ISSUE TITLE
Actual requirements for the executables are not clear

### ISSUE THREAD

**Issue by MichaelHuth** [goshhhy/486quake#1]
You requested benchmarks on twitter.

However for me the actual requirements are not very clear as the landscape of CPUs and configurations of that time is broad.

How much memory is required as minimum to get it running? (still 8 MB ?)
How much memory is required to get comparable benchmarks?
Do the 386 / 486 targets require an FPU?
What 486 CPU features are used? Does a Ti486DLC, NexGen Nx586 etc. count as 486 or 386?

**Comment by goshhhy** [comment]
memory requirements are the same as stock quake, 8mb. memory requirements may be lowered in the future, as i might pull work from my other project (uquake)[https://github.com/uquake] which attempts to lower memory requirements. if you have at least the minimum, then this is enough to test with.

just like original quake, the 486 and 386 variants do require a FPU. I do not plan to alleviate this requirement.

the optimizations are more about instruction scheduling than about individual instruction support. handwritten assembly routines do not, as far as i am aware, use any instructions beyond what the 386 supports. this may change in the future. most optimizations for the 486 will also benefit the 386, but there is still a large performance gap between the two, so i do not expect a 386 to ever reach playability.

the 486 binaries could possibly have BSWAP, CMPXCHG, and XADD generated by the compiler. the 586 binaries could have CMPXCHG8B generated by the compiler, but this is unlikely, and i have not seen this yet. the 686 binaries will very likely have CMOVEcc instructions generated.

a NexGen Nx586 will not work unless it is paired with a Nx587 FPU or otherwise has one integrated. It is my understanding that both of those are extremely uncommon.

a Cyrix 486DLC or its rebrand the Ti486DLC can be considered a very low-end 486 for the purposes of binary selection, but will likely not perform significantly better than a similarly clocked 386.

**Comment by goshhhy** [comment]
in the future when i have more data on these processors i will attempt to fill out the readme with a guide on what processors are expected to work with what binaries, and how well, but this is still a very early and experimental project.

**Comment by MichaelHuth** [comment]
Thanks for the clarification. I will try on a few machines.
